# Sets log defines.
# target_name - Target name.
# log_level - Log level. Allowed values: Verbose, Debug, Info, Warning, Error, Exception. "" means no logs.
# stacktrace_level - Log stacktrace level. Allowed values: Verbose, Debug, Info, Warning, Error, Exception. "" means no log stracktraces.
# console - If it's true, logs to a standard console are allowed.
# platform_console - If it's true, logs to a platform console are allowed. The platform must support a platform console.
function(pony_set_log_defines target_name log_level stacktrace_level console platform_console)
	function(get_sublist log_level sublist)
		set(LOG_LEVELS Verbose Debug Info Warning Error Exception)
		set(LOG_INDEX -1)
		set(i 0)
		foreach(LEVEL IN LISTS LOG_LEVELS)
			if("${LEVEL}" STREQUAL "${log_level}")
				set(LOG_INDEX ${i})
				break()
			endif()
			math(EXPR i "${i} + 1")
		endforeach()
		if(index EQUAL -1)
			message(FATAL_ERROR "Incorrect log level: ${log_level}")
		endif()

		list(LENGTH LOG_LEVELS LOG_LEVELS_LEN)
		math(EXPR num_elements "${LOG_LEVELS_LEN} - ${LOG_INDEX}")
		list(SUBLIST LOG_LEVELS ${LOG_INDEX} ${LOG_LEVELS_LEN} CURRENT_LOG_LEVELS)
		set(${sublist} ${CURRENT_LOG_LEVELS} PARENT_SCOPE)
	endfunction()

	function(set_log_options target_name log_level)
		if(log_level)
			get_sublist(${log_level} CURRENT_LOG_LEVELS)
			message(STATUS "Setting log defines: ${CURRENT_LOG_LEVELS}")
			foreach(LEVEL IN LISTS CURRENT_LOG_LEVELS)
				if(LEVEL STREQUAL Verbose)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_VERBOSE)
				elseif(LEVEL STREQUAL Debug)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_DEBUG)
				elseif(LEVEL STREQUAL Info)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_INFO)
				elseif(LEVEL STREQUAL Warning)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_WARNING)
				elseif(LEVEL STREQUAL Error)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_ERROR)
				elseif(LEVEL STREQUAL Exception)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_EXCEPTION)
				endif()
			endforeach()
		endif()
	endfunction()

	function(set_stacktrace_options target_name stacktrace_level)
		if(stacktrace_level)
			get_sublist(${stacktrace_level} CURRENT_STACKTRACE_LEVELS)
			message(STATUS "Setting log stacktrace defines: ${CURRENT_STACKTRACE_LEVELS}")
			foreach(LEVEL IN LISTS CURRENT_STACKTRACE_LEVELS)
				if(LEVEL STREQUAL Verbose)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_STACKTRACE_VERBOSE)
				elseif(LEVEL STREQUAL Debug)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_STACKTRACE_DEBUG)
				elseif(LEVEL STREQUAL Info)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_STACKTRACE_INFO)
				elseif(LEVEL STREQUAL Warning)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_STACKTRACE_WARNING)
				elseif(LEVEL STREQUAL Error)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_STACKTRACE_ERROR)
				elseif(LEVEL STREQUAL Exception)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_STACKTRACE_EXCEPTION)
				endif()
			endforeach()
		endif()
	endfunction()

	if(NOT TARGET ${target_name})
		message(FATAL_ERROR "${target_name} isn't a target")
	endif()

	if(console)
		message(STATUS "Setting console defines")
		target_compile_definitions(${target_name} PRIVATE PONY_CONSOLE_LOG)
	endif()
	if(platform_console)
		if (PONY_WINCORE)
			message(STATUS "Setting platform console defines")
			target_compile_definitions(${target_name} PRIVATE PONY_PLATFORM_CONSOLE_LOG)
		else()
			message(FATAL_ERROR "Current platform doesn't support a platform console.")
		endif()
	endif()

	set_log_options(${target_name} ${log_level})
	set_stacktrace_options(${target_name} ${stacktrace_level})
endfunction()
