cmake_minimum_required (VERSION 3.31)
message(STATUS "Configuring Pony Engine")

if(PROJECT_NAME)
	message(VERBOSE "Configuring as sub-project")
	set(PONY_IS_SUBPROJECT TRUE)
else()
	message(VERBOSE "Configuring as main project")
	set(PONY_IS_SUBPROJECT FALSE)
endif()

message(VERBOSE "Configuring environment")
if(NOT PONY_IS_SUBPROJECT)
	set(CMAKE_CXX_STANDARD 23)
	set(CMAKE_CXX_STANDARD_REQUIRED ON)
	set(CMAKE_CXX_EXTENSIONS OFF)
	set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "0e5b6991-d74f-4b3d-a41c-cf096e0b2508")
	set(CMAKE_CXX_MODULE_STD ON)
endif()

set(PONY_ENGINE_NAME "PonyEngine" CACHE STRING "Pony Engine name." FORCE)
set(PONY_ENGINE_VERSION_MAJOR "0" CACHE STRING "Pony Engine major version." FORCE)
set(PONY_ENGINE_VERSION_MINOR "1" CACHE STRING "Pony Engine minor version." FORCE)
set(PONY_ENGINE_VERSION_PATCH "1" CACHE STRING "Pony Engine patch version." FORCE)
set(PONY_ENGINE_VERSION_TWEAK "0" CACHE STRING "Pony Engine tweak version." FORCE)
set(PONY_ENGINE_VERSION "${PONY_ENGINE_VERSION_MAJOR}.${PONY_ENGINE_VERSION_MINOR}.${PONY_ENGINE_VERSION_PATCH}.${PONY_ENGINE_VERSION_TWEAK}" CACHE STRING "Pony Engine version." FORCE)
set(PONY_ENGINE_TITLE "Pony Engine" CACHE STRING "Pony Engine title." FORCE)

set(PONY_ENGINE_APPLICATION_ICON_COLLECTION_PATH "${CMAKE_CURRENT_LIST_DIR}/Logo")

set(PONY_BUILD_MODE "Runtime" CACHE STRING "Project build mode. Must be one of these values: Runtime, Tools or Editor.")
if(NOT PONY_BUILD_MODE STREQUAL "Runtime" AND NOT PONY_BUILD_MODE STREQUAL "Tools" AND NOT PONY_BUILD_MODE STREQUAL "Editor")
	message(FATAL_ERROR "Incorrect PONY_BUILD_MODE: '${PONY_BUILD_MODE}'. Must be 'Runtime', 'Tools' or 'Editor'")
endif()

if(PONY_BUILD_MODE STREQUAL "Runtime")
	message(STATUS "Configuring engine project")
	project(${PONY_ENGINE_NAME} VERSION ${PONY_ENGINE_VERSION} LANGUAGES CXX)
	add_subdirectory("Engine")

	if(NOT PONY_IS_SUBPROJECT)
		include("CMake/EngineModulePostConfiguration.cmake")

		if(PONY_ENGINE_TESTING)
			message(STATUS "Configuring test project")
			add_subdirectory("Tests/Engine")
		endif()
	endif()
elseif(PONY_BUILD_MODE STREQUAL "Tools")
	message(STATUS "Configuring tools project")
	project("${PONY_ENGINE_NAME}Tools" VERSION ${PONY_ENGINE_VERSION} LANGUAGES CXX)
	add_subdirectory("Tools")
elseif(PONY_BUILD_MODE STREQUAL "Editor")
	message(FATAL_ERROR "Editor build not implemented yet")
endif()
