message(STATUS "Configuring engine")

include("CMake/Target.cmake")
include("CMake/Path.cmake")
include("CMake/Project.cmake")
include("CMake/Resource.cmake")
include("CMake/Shader.cmake")

set(PONY_COMPANY_NAME "PonyEngine" CACHE STRING "Company name. It's used to create project folders. So, it must be a valid directory name.")
set(PONY_PROJECT_NAME "PonyEngineGame" CACHE STRING "Project name. It's used to create project folders. So, it must be a valid directory name. It's also used for an executable name.")
set(PONY_PROJECT_VERSION_MAJOR "0" CACHE STRING "Project major version.")
set(PONY_PROJECT_VERSION_MINOR "0" CACHE STRING "Project minor version.")
set(PONY_PROJECT_VERSION_PATCH "0" CACHE STRING "Project patch version.")
set(PONY_PROJECT_VERSION_TWEAK "0" CACHE STRING "Project tweak version.")
set(PONY_COMPANY_TITLE "Pony Engine" CACHE STRING "Company title. It's used in GUI only. May be any non-empty string.")
set(PONY_PROJECT_TITLE "Pony Engine Game" CACHE STRING "Project title. It's used in GUI only. May be any non-empty string.")
set(PONY_PROJECT_VERSION "${PONY_PROJECT_VERSION_MAJOR}.${PONY_PROJECT_VERSION_MINOR}.${PONY_PROJECT_VERSION_PATCH}.${PONY_PROJECT_VERSION_TWEAK}")
pony_validate_name(PONY_COMPANY_NAME)
pony_validate_name(PONY_PROJECT_NAME)
pony_validate_version(PONY_PROJECT_VERSION)
pony_validate_title(PONY_COMPANY_TITLE)
pony_validate_title(PONY_PROJECT_TITLE)

option(PONY_ENGINE_CUSTOM_PLATFORM "If OFF, the engine automatically detects and configures supported platforms. If ON, the engine skips platform detection and a custom platform configuration must be provided." OFF)
option(PONY_ENGINE_CUSTOM_COMPILER "If OFF, the engine automatically detects and configures supported compilers. If ON, the engine skips compiler detection and a custom compiler configuration must be provided." OFF)

add_subdirectory("Modules")

if(NOT PONY_ENGINE_CUSTOM_PLATFORM)
	add_subdirectory("Platforms")
endif()
