/***************************************************
 * MIT License                                     *
 *                                                 *
 * Copyright (c) 2023-present Vladimir Popov       *
 *                                                 *
 * Email: zor1994@gmail.com                        *
 * Repo: https://github.com/ZorPastaman/PonyEngine *
 ***************************************************/

#pragma once

#include "Layout.h"

#define PONY_INPUT_MOUSE "Mouse"

#define PONY_INPUT_MOUSE_BUTTON PONY_INPUT_PATH_BUTTON
#define PONY_INPUT_MOUSE_BUTTON_PATH PONY_INPUT_MOUSE PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_MOUSE_BUTTON
#define PONY_INPUT_MOUSE_BUTTON_1_PATH PONY_INPUT_MOUSE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR "1"
#define PONY_INPUT_MOUSE_BUTTON_2_PATH PONY_INPUT_MOUSE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR "2"
#define PONY_INPUT_MOUSE_BUTTON_3_PATH PONY_INPUT_MOUSE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR "3"
#define PONY_INPUT_MOUSE_BUTTON_4_PATH PONY_INPUT_MOUSE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR "4"
#define PONY_INPUT_MOUSE_BUTTON_5_PATH PONY_INPUT_MOUSE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR "5"

#define PONY_INPUT_MOUSE_WHEEL "Wheel"
#define PONY_INPUT_MOUSE_WHEEL_PATH PONY_INPUT_MOUSE PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_MOUSE_WHEEL
#define PONY_INPUT_MOUSE_WHEEL_HORIZONTAL_PATH PONY_INPUT_MOUSE_WHEEL_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_HORIZONTAL
#define PONY_INPUT_MOUSE_WHEEL_VERTICAL_PATH PONY_INPUT_MOUSE_WHEEL_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_VERTICAL

#define PONY_INPUT_MOUSE_AXIS PONY_INPUT_PATH_AXIS
#define PONY_INPUT_MOUSE_AXIS_PATH PONY_INPUT_MOUSE PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_MOUSE_AXIS
#define PONY_INPUT_MOUSE_AXIS_X_PATH PONY_INPUT_MOUSE_AXIS_PATH PONY_INPUT_PATH_SEPARATOR_STR "X"
#define PONY_INPUT_MOUSE_AXIS_Y_PATH PONY_INPUT_MOUSE_AXIS_PATH PONY_INPUT_PATH_SEPARATOR_STR "Y"
