/***************************************************
 * MIT License                                     *
 *                                                 *
 * Copyright (c) 2023-present Vladimir Popov       *
 *                                                 *
 * Email: zor1994@gmail.com                        *
 * Repo: https://github.com/ZorPastaman/PonyEngine *
 ***************************************************/

#pragma once

#include "Layout.h"

#define PONY_INPUT_GAMEPAD "Gamepad"

#define PONY_INPUT_XBOX "Xbox"
#define PONY_INPUT_GAMEPAD_XBOX PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_XBOX

#define PONY_INPUT_PLAYSTATION "PlayStation"
#define PONY_INPUT_GAMEPAD_PLAYSTATION PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PLAYSTATION

#define PONY_INPUT_GAMEPAD_DPAD "D-Pad"
#define PONY_INPUT_GAMEPAD_DPAD_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_DPAD
#define PONY_INPUT_GAMEPAD_DPAD_LEFT_PATH PONY_INPUT_GAMEPAD_DPAD_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_LEFT
#define PONY_INPUT_GAMEPAD_DPAD_RIGHT_PATH PONY_INPUT_GAMEPAD_DPAD_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_RIGHT
#define PONY_INPUT_GAMEPAD_DPAD_DOWN_PATH PONY_INPUT_GAMEPAD_DPAD_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_DOWN
#define PONY_INPUT_GAMEPAD_DPAD_UP_PATH PONY_INPUT_GAMEPAD_DPAD_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_UP

#define PONY_INPUT_GAMEPAD_FACE_BUTTON "FaceButton"
#define PONY_INPUT_GAMEPAD_FACE_BUTTON_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_FACE_BUTTON
#define PONY_INPUT_GAMEPAD_FACE_BUTTON_LEFT_PATH PONY_INPUT_GAMEPAD_FACE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_LEFT
#define PONY_INPUT_GAMEPAD_FACE_BUTTON_RIGHT_PATH PONY_INPUT_GAMEPAD_FACE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_RIGHT
#define PONY_INPUT_GAMEPAD_FACE_BUTTON_DOWN_PATH PONY_INPUT_GAMEPAD_FACE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_DOWN
#define PONY_INPUT_GAMEPAD_FACE_BUTTON_UP_PATH PONY_INPUT_GAMEPAD_FACE_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_UP

#define PONY_INPUT_GAMEPAD_BACK_BUTTON "BackButton"
#define PONY_INPUT_GAMEPAD_BACK_BUTTON_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_BACK_BUTTON
#define PONY_INPUT_GAMEPAD_BACK_BUTTON_LEFT_PATH PONY_INPUT_GAMEPAD_BACK_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_LEFT
#define PONY_INPUT_GAMEPAD_BACK_BUTTON_RIGHT_PATH PONY_INPUT_GAMEPAD_BACK_BUTTON_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_RIGHT

#define PONY_INPUT_GAMEPAD_TRIGGER "Trigger"
#define PONY_INPUT_GAMEPAD_TRIGGER_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_TRIGGER
#define PONY_INPUT_GAMEPAD_TRIGGER_LEFT_PATH PONY_INPUT_GAMEPAD_TRIGGER_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_LEFT
#define PONY_INPUT_GAMEPAD_TRIGGER_RIGHT_PATH PONY_INPUT_GAMEPAD_TRIGGER_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_RIGHT

#define PONY_INPUT_GAMEPAD_LEFT_STICK PONY_INPUT_PATH_LEFT "Stick"
#define PONY_INPUT_GAMEPAD_LEFT_STICK_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_LEFT_STICK
#define PONY_INPUT_GAMEPAD_LEFT_STICK_HORIZONTAL_PATH PONY_INPUT_GAMEPAD_LEFT_STICK_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_HORIZONTAL
#define PONY_INPUT_GAMEPAD_LEFT_STICK_VERTICAL_PATH PONY_INPUT_GAMEPAD_LEFT_STICK_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_VERTICAL
#define PONY_INPUT_GAMEPAD_LEFT_STICK_BUTTON_PATH PONY_INPUT_GAMEPAD_LEFT_STICK_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_BUTTON

#define PONY_INPUT_GAMEPAD_RIGHT_STICK PONY_INPUT_PATH_RIGHT "Stick"
#define PONY_INPUT_GAMEPAD_RIGHT_STICK_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_RIGHT_STICK
#define PONY_INPUT_GAMEPAD_RIGHT_STICK_HORIZONTAL_PATH PONY_INPUT_GAMEPAD_RIGHT_STICK_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_HORIZONTAL
#define PONY_INPUT_GAMEPAD_RIGHT_STICK_VERTICAL_PATH PONY_INPUT_GAMEPAD_RIGHT_STICK_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_VERTICAL
#define PONY_INPUT_GAMEPAD_RIGHT_STICK_BUTTON_PATH PONY_INPUT_GAMEPAD_RIGHT_STICK_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_BUTTON

#define PONY_INPUT_GAMEPAD_SYSTEM PONY_INPUT_PATH_SYSTEM
#define PONY_INPUT_GAMEPAD_SYSTEM_PATH PONY_INPUT_GAMEPAD PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_GAMEPAD_SYSTEM
#define PONY_INPUT_GAMEPAD_SYSTEM_MENU_PATH PONY_INPUT_GAMEPAD_SYSTEM_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_MENU
#define PONY_INPUT_GAMEPAD_SYSTEM_SELECT_PATH PONY_INPUT_GAMEPAD_SYSTEM_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_SELECT
#define PONY_INPUT_GAMEPAD_SYSTEM_GUIDE_PATH PONY_INPUT_GAMEPAD_SYSTEM_PATH PONY_INPUT_PATH_SEPARATOR_STR PONY_INPUT_PATH_GUIDE
