message(STATUS "Configuring engine modules")

option(PONY_ENGINE_APPLICATION "Enable PonyEngine.Application module" OFF)
option(PONY_ENGINE_APPLICATION_IMPL "Enable PonyEngine.Application.Impl module" OFF)
option(PONY_ENGINE_CORE "Enable PonyEngine.Core module" OFF)
option(PONY_ENGINE_FILE "Enable PonyEngine.File module" OFF)
option(PONY_ENGINE_FILE_IMPL "Enable PonyEngine.File.Impl module" OFF)
option(PONY_ENGINE_JOB "Enable PonyEngine.Job module" OFF)
option(PONY_ENGINE_JOB_IMPL "Enable PonyEngine.Job.Impl module" OFF)
option(PONY_ENGINE_LOG "Enable PonyEngine.Log module." OFF)
option(PONY_ENGINE_LOG_EXT "Enable PonyEngine.Log.Ext module." OFF)
option(PONY_ENGINE_LOG_IMPL "Enable PonyEngine.Log.Impl module." OFF)
option(PONY_ENGINE_LOG_CONSOLE_IMPL "Enable PonyEngine.Log.Console.Impl module." OFF)
option(PONY_ENGINE_LOG_FILE_IMPL "Enable PonyEngine.Log.File.Impl module." OFF)
option(PONY_ENGINE_LOG_PCONSOLE_IMPL "Enable PonyEngine.Log.PConsole.Impl module." OFF)
option(PONY_ENGINE_RAW_INPUT "Enable PonyEngine.RawInput module." OFF)
option(PONY_ENGINE_RAW_INPUT_EXT "Enable PonyEngine.RawInput.Ext module." OFF)
option(PONY_ENGINE_RAW_INPUT_IMPL "Enable PonyEngine.RawInput.Impl module." OFF)
option(PONY_ENGINE_RAW_INPUT_KEYBOARD_IMPL "Enable PonyEngine.RawInput.Keyboard.Impl module." OFF)
option(PONY_ENGINE_RAW_INPUT_MOUSE_IMPL "Enable PonyEngine.RawInput.Mouse.Impl module." OFF)
option(PONY_ENGINE_RAW_INPUT_XINPUT_IMPL "Enable PonyEngine.RawInput.XInput.Impl module." OFF)
option(PONY_ENGINE_RENDER_DEVICE "Enable PonyEngine.RenderDevice module." OFF)
option(PONY_ENGINE_RENDER_DEVICE_EXT "Enable PonyEngine.RenderDevice.Ext module." OFF)
option(PONY_ENGINE_RENDER_DEVICE_IMPL "Enable PonyEngine.RenderDevice.Impl module." OFF)
option(PONY_ENGINE_RENDER_DEVICE_D3D12_IMPL "Enable PonyEngine.RenderDevice.D3D12.Impl module." OFF)
option(PONY_ENGINE_RESOURCE "Enable PonyEngine.Resource module" OFF)
option(PONY_ENGINE_RESOURCE_EXT "Enable PonyEngine.Resource.Ext module" OFF)
option(PONY_ENGINE_RESOURCE_IMPL "Enable PonyEngine.Resource.Impl module" OFF)
option(PONY_ENGINE_RESOURCE_PACK "Enable PonyEngine.Resource.Pack module" OFF)
option(PONY_ENGINE_RESOURCE_PACK_IMPL "Enable PonyEngine.Resource.Pack.Impl module" OFF)
option(PONY_ENGINE_SHADER "Enable PonyEngine.Shader module" OFF)
option(PONY_ENGINE_SURFACE "Enable PonyEngine.Surface module." OFF)
option(PONY_ENGINE_SURFACE_IMPL "Enable PonyEngine.Surface.Impl module." OFF)
option(PONY_ENGINE_TIME "Enable PonyEngine.Time module." OFF)
option(PONY_ENGINE_TIME_IMPL "Enable PonyEngine.Time.Impl module." OFF)
option(PONY_ENGINE_WINAPI_INPUT "Enable PonyEngine.WinAPIInput module." OFF)
option(PONY_ENGINE_WINAPI_INPUT_IMPL "Enable PonyEngine.WinAPIInput.Impl module." OFF)
option(PONY_ENGINE_WORLD "Enable PonyEngine.World module" OFF)
option(PONY_ENGINE_WORLD_IMPL "Enable PonyEngine.World.Impl module" OFF)

if(PONY_ENGINE_CORE)
	add_subdirectory("Core")
endif()
if(PONY_ENGINE_LOG)
	add_subdirectory("Log")
endif()
if(PONY_ENGINE_APPLICATION)
	add_subdirectory("Application")
endif()
if(PONY_ENGINE_APPLICATION_IMPL)
	add_subdirectory("Application.Impl")
endif()

if(PONY_ENGINE_LOG_EXT)
	add_subdirectory("Log.Ext")
endif()
if(PONY_ENGINE_LOG_IMPL)
	add_subdirectory("Log.Impl")
endif()
if(PONY_ENGINE_LOG_CONSOLE_IMPL)
	add_subdirectory("Log.Console.Impl")
endif()
if(PONY_ENGINE_LOG_PCONSOLE_IMPL)
	add_subdirectory("Log.PConsole.Impl")
endif()
if(PONY_ENGINE_LOG_FILE_IMPL)
	add_subdirectory("Log.File.Impl")
endif()

if(PONY_ENGINE_TIME)
	add_subdirectory("Time")
endif()
if(PONY_ENGINE_TIME_IMPL)
	add_subdirectory("Time.Impl")
endif()

if(PONY_ENGINE_JOB)
	add_subdirectory("Job")
endif()
if(PONY_ENGINE_JOB_IMPL)
	add_subdirectory("Job.Impl")
endif()

if(PONY_ENGINE_FILE)
	add_subdirectory("File")
endif()
if(PONY_ENGINE_FILE_IMPL)
	add_subdirectory("File.Impl")
endif()

if(PONY_ENGINE_RESOURCE)
	add_subdirectory("Resource")
endif()
if(PONY_ENGINE_RESOURCE_EXT)
	add_subdirectory("Resource.Ext")
endif()
if(PONY_ENGINE_RESOURCE_IMPL)
	add_subdirectory("Resource.Impl")
endif()
if(PONY_ENGINE_RESOURCE_PACK)
	add_subdirectory("Resource.Pack")
endif()
if(PONY_ENGINE_RESOURCE_PACK_IMPL)
	add_subdirectory("Resource.Pack.Impl")
endif()

if(PONY_ENGINE_SURFACE)
	add_subdirectory("Surface")
endif()
if(PONY_ENGINE_SURFACE_IMPL)
	add_subdirectory("Surface.Impl")
endif()

if(PONY_ENGINE_RENDER_DEVICE)
	add_subdirectory("RenderDevice")
endif()
if(PONY_ENGINE_RENDER_DEVICE_EXT)
	add_subdirectory("RenderDevice.Ext")
endif()
if(PONY_ENGINE_RENDER_DEVICE_IMPL)
	add_subdirectory("RenderDevice.Impl")
endif()
if(PONY_ENGINE_RENDER_DEVICE_D3D12_IMPL)
	add_subdirectory("RenderDevice.D3D12.Impl")
endif()
if(PONY_ENGINE_SHADER)
	add_subdirectory("Shader")
endif()

if(PONY_ENGINE_WINAPI_INPUT)
	add_subdirectory("WinAPIInput")
endif()
if(PONY_ENGINE_WINAPI_INPUT_IMPL)
	add_subdirectory("WinAPIInput.Impl")
endif()
if(PONY_ENGINE_RAW_INPUT)
	add_subdirectory("RawInput")
endif()
if(PONY_ENGINE_RAW_INPUT_EXT)
	add_subdirectory("RawInput.Ext")
endif()
if(PONY_ENGINE_RAW_INPUT_IMPL)
	add_subdirectory("RawInput.Impl")
endif()
if(PONY_ENGINE_RAW_INPUT_KEYBOARD_IMPL)
	add_subdirectory("RawInput.Keyboard.Impl")
endif()
if(PONY_ENGINE_RAW_INPUT_MOUSE_IMPL)
	add_subdirectory("RawInput.Mouse.Impl")
endif()
if(PONY_ENGINE_RAW_INPUT_XINPUT_IMPL)
	add_subdirectory("RawInput.XInput.Impl")
endif()

if(PONY_ENGINE_WORLD)
	add_subdirectory("World")
endif()
if(PONY_ENGINE_WORLD_IMPL)
	add_subdirectory("World.Impl")
endif()
