message(STATUS "Configuring Windows x64 MSVC toolchain")
message(VERBOSE "Configuring platform")
include("${CMAKE_CURRENT_LIST_DIR}/Windows-x64.cmake")

message(VERBOSE "Configuring compiler")
set(CMAKE_CXX_COMPILER "cl.exe")
set(PONY_ENGINE_MSVC TRUE)

set(CMAKE_CXX_FLAGS "/DWIN32 /D_WINDOWS /arch:AVX2 /EHsc /fp:fast /GR /permissive- /utf-8 /W3 /Zc:__cplusplus /Zc:preprocessor /Zc:throwingNew" CACHE STRING "Flags used by the CXX compiler during all build types." FORCE)
set(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "Flags used by the CXX compiler during DEBUG builds." FORCE)
set(CMAKE_CXX_FLAGS_RELEASE "/DNDEBUG" CACHE STRING "Flags used by the CXX compiler during RELEASE builds." FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/DNDEBUG" CACHE STRING "Flags used by the CXX compiler during RELWITHDEBINFO builds." FORCE)
set(CMAKE_EXE_LINKER_FLAGS "" CACHE STRING "Flags used by the linker during all build types." FORCE)
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/debug" CACHE STRING "Flags used by the linker during DEBUG builds." FORCE)
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "" CACHE STRING "Flags used by the linker during RELEASE builds." FORCE)
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/debug" CACHE STRING "Flags used by the linker during RELWITHDEBINFO builds." FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "" CACHE STRING "Flags used by the linker during all build types." FORCE)
set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "/debug" CACHE STRING "Flags used by the linker during DEBUG builds." FORCE)
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "" CACHE STRING "Flags used by the linker during RELEASE builds." FORCE)
set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "/debug" CACHE STRING "Flags used by the linker during RELWITHDEBINFO builds." FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "" CACHE STRING "Flags used by the linker during all build types." FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/debug" CACHE STRING "Flags used by the linker during DEBUG builds." FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "" CACHE STRING "Flags used by the linker during RELEASE builds." FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "/debug" CACHE STRING "Flags used by the linker during RELWITHDEBINFO builds." FORCE)

set(PONY_COMPILE_FLAGS_DEBUG /Ob0 /Od /RTC1)
set(PONY_COMPILE_FLAGS_RELEASE /GL /Gw /Gy /Ob3 /O2 /Zc:inline)
set(PONY_LINK_FLAGS_DEBUG /INCREMENTAL /OPT:NOREF)
set(PONY_LINK_FLAGS_RELEASE /INCREMENTAL:NO /LTCG /OPT:REF /OPT:ICF)

include("${CMAKE_CURRENT_LIST_DIR}/Compiler.cmake")
