# Sets log defines that must be applied to all targets.
function(pony_set_global_log_defines)
	if(PONY_CONSOLE_LOG)
		add_compile_definitions(PONY_CONSOLE_LOG)
	endif()
	if(PONY_SYSTEM_CONSOLE_LOG)
		add_compile_definitions(PONY_SYSTEM_CONSOLE_LOG)
	endif()
endfunction()

# Sets log defines by a log level.
# target_name - Target name.
# is_engine_target - Is the target an engine target?
function(pony_set_log_mask target_name is_engine_target)
	function(set_options target_name log_level)
		if(log_level)
			set(LOG_LEVELS Verbose Debug Info Warning Error Exception)
			set(LOG_INDEX -1)
			set(i 0)
			foreach(LEVEL IN LISTS LOG_LEVELS)
				if("${LEVEL}" STREQUAL "${log_level}")
					set(LOG_INDEX ${i})
					break()
				endif()
				math(EXPR i "${i} + 1")
			endforeach()
			if(index EQUAL -1)
				message(FATAL_ERROR "Incorrect log level")
			endif()

			list(LENGTH LOG_LEVELS LOG_LEVELS_LEN)
			math(EXPR num_elements "${LOG_LEVELS_LEN} - ${LOG_INDEX}")
			list(SUBLIST LOG_LEVELS ${LOG_INDEX} ${LOG_LEVELS_LEN} CURRENT_LOG_LEVELS)
			message(STATUS "Setting log defines: ${CURRENT_LOG_LEVELS}")
			foreach(LEVEL IN LISTS CURRENT_LOG_LEVELS)
				if(LEVEL STREQUAL Verbose)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_VERBOSE)
				elseif(LEVEL STREQUAL Debug)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_DEBUG)
				elseif(LEVEL STREQUAL Info)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_INFO)
				elseif(LEVEL STREQUAL Warning)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_WARNING)
				elseif(LEVEL STREQUAL Error)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_ERROR)
				elseif(LEVEL STREQUAL Exception)
					target_compile_definitions(${target_name} PRIVATE PONY_LOG_EXCEPTION)
				endif()
			endforeach()
		endif()
	endfunction()

	if(is_engine_target)
		set_options(${target_name} ${PONY_ENGINE_LOG_LEVEL})
	else()
		set_options(${target_name} ${PONY_GAME_LOG_LEVEL})
	endif()
endfunction()
