function(compile_shader_with_dxc source output)
	set(options SPIRV)
	set(oneValueArgs PROFILE ROOT_SIG_VER ENTRY DEBUG OPTIMIZATION SPIRV_TARGET PDB_DIR)
	set(multiValueArgs DEFINES INCLUDES ADDITIONAL_PARAMS)
	cmake_parse_arguments(PARSE_ARGV 0 dxc_arg "${options}" "${oneValueArgs}" "${multiValueArgs}")

	if(NOT source)
		message(FATAL_ERROR "Empty source")
	endif()
	if(NOT output)
		message(FATAL_ERROR "Empty output")
	endif()
	if(NOT dxc_arg_PROFILE)
		message(FATAL_ERROR "Empty profile")
	endif()

	if(dxc_arg_SPIRV_TARGET AND NOT dxc_arg_SPIRV)
		message(FATAL_ERROR "SPIR-V target is set in non-spirv build")
	endif()

	if(NOT DEFINED dxc_arg_DEBUG)
		if(CMAKE_BUILD_TYPE STREQUAL "Debug")
			set(dxc_arg_DEBUG ON)
		else()
			set(dxc_arg_DEBUG OFF)
		endif()
	endif()
	if(dxc_arg_PDB_DIR AND NOT dxc_arg_DEBUG)
		message(FATAL_ERROR "PDB directory is set in non-debug build")
	endif()

	get_filename_component(source_abs ${source} ABSOLUTE)
	get_filename_component(output_abs ${output} ABSOLUTE)

	if(NOT dxc_arg_ENTRY)
		set(dxc_arg_ENTRY "main")
	endif()

	get_filename_component(output_dir ${output_abs} DIRECTORY)
	file(MAKE_DIRECTORY ${output_dir})
	set(DXC_OPTIONS -T ${dxc_arg_PROFILE} -E ${dxc_arg_ENTRY} -Fo ${output_abs})
	if(dxc_arg_ROOT_SIG_VER)
		list(APPEND DXC_OPTIONS -force-rootsig-ver ${dxc_arg_ROOT_SIG_VER})
	endif()
	if(dxc_arg_OPTIMIZATION)
		list(APPEND DXC_OPTIONS -O${dxc_arg_OPTIMIZATION})
	endif()
	foreach(define ${dxc_arg_DEFINES})
		list(APPEND DXC_OPTIONS -D ${define})
	endforeach()
	foreach(include ${dxc_arg_INCLUDES})
		get_filename_component(include_abs ${include} ABSOLUTE)
		list(APPEND DXC_OPTIONS -I ${include_abs})
	endforeach()

	if(dxc_arg_SPIRV)
		list(APPEND DXC_OPTIONS -spirv)
	endif()
	if(dxc_arg_SPIRV_TARGET)
		list(APPEND DXC_OPTIONS -fspv-target-env=${dxc_arg_SPIRV_TARGET})
	endif()

	if(dxc_arg_DEBUG)
		list(APPEND DXC_OPTIONS -Zi)
	else()
		list(APPEND DXC_OPTIONS -Qstrip_debug -Qstrip_reflect)
	endif()
	if(dxc_arg_PDB_DIR)
		get_filename_component(pdb_dir_abs ${dxc_arg_PDB_DIR} ABSOLUTE)
		file(MAKE_DIRECTORY ${pdb_dir_abs})
		list(APPEND DXC_OPTIONS -Fd ${pdb_dir_abs})
	else()
		list(APPEND DXC_OPTIONS -Qembed_debug)
	endif()

	set(DXC_DEP_FILE ${output_abs}.d)
	add_custom_command(COMMAND dxc ${DXC_OPTIONS} -MD -MF ${DXC_DEP_FILE} ${source_abs} && dxc ${DXC_OPTIONS} ${source_abs}
		DEPENDS ${source_abs}
		OUTPUT ${output_abs}
		DEPFILE ${DXC_DEP_FILE}
		COMMENT "Compiling ${source} to ${output} with dxc"
		VERBATIM
	)
endfunction()
